### ISSUE TITLE
What happens on 0.1.0?

### ISSUE THREAD

**Issue by chulkilee** [dominictarr/map-stream#13] opened 2014-12-19 02:39 UTC
Some modules depend on 0.1.0 (e.g. gulp-eslint). I cannot find it from [the npm page](https://www.npmjs.com/package/map-stream) but npm info includes the version.

```
{ name: 'map-stream',
  description: 'construct pipes of streams of events',
  'dist-tags': { latest: '0.0.5' },
  versions:
   [ '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.1.0' ],
  maintainers: 'dominictarr <dominic.tarr@gmail.com>',
  time:
   { modified: '2014-11-03T17:03:20.755Z',
     created: '2012-08-18T13:07:31.578Z',
     '0.0.1': '2012-08-18T13:07:33.660Z',
     '0.0.2': '2013-01-17T04:54:50.995Z',
     '0.0.3': '2013-09-24T03:42:27.320Z',
     '0.0.4': '2013-12-07T02:05:06.804Z',
     '0.1.0': '2014-01-09T07:15:35.544Z',
     '0.0.5': '2014-11-03T17:03:20.755Z' },
  author: 'Dominic Tarr <dominic.tarr@gmail.com> (http://dominictarr.com)',
  repository:
   { type: 'git',
     url: 'git://github.com/dominictarr/map-stream.git' },
  users:
   { brianloveswords: true,
     dukewan: true,
     lapanoid: true },
  homepage: 'http://github.com/dominictarr/map-stream',
  bugs: { url: 'https://github.com/dominictarr/map-stream/issues' },
  license: 'MIT',
  readmeFilename: 'readme.markdown',
  version: '0.0.5',
  dependencies: {},
  devDependencies:
   { asynct: '*',
     'it-is': '1',
     ubelt: '~2.9',
     'stream-spec': '~0.2',
     'event-stream': '~2.1',
     from: '0.0.2' },
  scripts: { test: 'asynct test/' },
  gitHead: '336f8ecdce81f5c66001646871ca73584879b419',
  dist:
   { shasum: '80ffe0f588da32bf006b7f12d9197c5b8725df1c',
     tarball: 'http://registry.npmjs.org/map-stream/-/map-stream-0.0.5.tgz' },
  directories: {} }
```

**Comment by panuhorsmalahti** [comment] 2015-01-06 12:59
Yeah, it's weird. My project depends on 0.1.0, and I'm unsure if I should "fall back" to 0.0.5.

**Comment by slang800** [comment] 2015-04-10 04:12
I think this is fixed now, and it's not a bug in this package. Close?

**Closed** 2015-04-10 04:45 UTC

**Comment by nilpath** [comment] 2015-04-10 13:00
I'm still seeing this problem

**Comment by dominictarr** [comment] 2015-04-10 22:02
I don't know why there is a 0.1.0, but I downloaded it from npm and it contains exactly the same actual code as 0.0.5, so it's weird but there are no problems

**Comment by nilpath** [comment] 2015-04-10 22:27
well I had some problems when doing a npm install, trying to install gulp-sass wich is using "~0.1.0". I got a lot of module not fond.

however, it seemed to resolve itself after clearing the node_modules folder.
